/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import excepciones.Excepcion;
import ejerciciobasedatos.EjercicioBaseDatos;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import modelo.Persona;
/**
 *
 * @author txaber
 */
public class VentanaOperacion extends javax.swing.JFrame {

    private String operacion = "alta";
    private ArrayList<Persona> lista;
    private int indiceActual;
    /**
     * Creates new form VentanaOperacion
     */
    public VentanaOperacion() {
        initComponents();
        setLocationRelativeTo(null);
        
        bAnterior.setVisible(false);
        bPosterior.setVisible(false);
        bSalir.setVisible(false);
    }
    
    public VentanaOperacion(Persona p) {
        initComponents();
        setLocationRelativeTo(null);
        tfNombre.setText(p.getNombre());
        tfEdad.setText(String.valueOf(p.getEdad()));
        tfProfesion.setText(p.getProfesion());
        tfTelefono.setText(String.valueOf(p.getTelefono()));
        this.operacion="consulta";
        bAnterior.setVisible(false);
        bPosterior.setVisible(false);
        bSalir.setVisible(false);
        
    }
    
    public VentanaOperacion(ArrayList<Persona> lista) {
        initComponents();
        setLocationRelativeTo(null);
        this.lista = lista;
        
        tfNombre.setText(lista.get(0).getNombre());
        tfEdad.setText(String.valueOf(lista.get(0).getEdad()));
        tfProfesion.setText(lista.get(0).getProfesion());
        tfTelefono.setText(String.valueOf(lista.get(0).getTelefono()));
        indiceActual = 0;
        
        bAceptar.setVisible(false);
        tfNombre.setEditable(false);
        tfEdad.setEditable(false);
        tfProfesion.setEditable(false);
        tfTelefono.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfEdad = new javax.swing.JTextField();
        tfProfesion = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        bPosterior = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Personas");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Profesion");

        jLabel5.setText("Telefono");

        bPosterior.setText(">");
        bPosterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPosteriorActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bAnterior.setText("<");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bAceptar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(78, 78, 78)
                                    .addComponent(tfProfesion))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(81, 81, 81)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(tfTelefono)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(103, 103, 103)
                                            .addComponent(tfEdad))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(bAnterior)
                                            .addGap(18, 18, 18)
                                            .addComponent(bPosterior)
                                            .addGap(18, 18, 18)
                                            .addComponent(bSalir)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfProfesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPosterior)
                    .addComponent(bSalir)
                    .addComponent(bAnterior))
                .addGap(30, 30, 30)
                .addComponent(bAceptar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            if (operacion.equals("alta")) {
                //validaciones
                if (tfNombre.getText().isEmpty() || tfEdad.getText().isEmpty() || tfProfesion.getText().isEmpty() || tfTelefono.getText().isEmpty())
                    throw new Excepcion("todos los datos mostrados son obligatorios y falta alguno para rellenar");
                
                
                
                EjercicioBaseDatos.insertar(tfNombre.getText(),Integer.parseInt(tfEdad.getText()),tfProfesion.getText(),Integer.parseInt(tfTelefono.getText()));
                JOptionPane.showMessageDialog(this, "persona añadida con exito");
            }
            else {
                EjercicioBaseDatos.volver();
            }
        }
        catch (Excepcion e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "problemas con los datos numericos");
        }
        catch (MySQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "problemas: hay una persona que ya tiene ese nombre");
        }
        catch(Exception e) {
            System.out.println(e.getMessage()+e.getClass());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        
        if (!(indiceActual == 0)) {
            indiceActual --;
            tfNombre.setText(lista.get(indiceActual).getNombre());
            tfEdad.setText(String.valueOf(lista.get(indiceActual).getEdad()));
            tfProfesion.setText(lista.get(indiceActual).getProfesion());
            tfTelefono.setText(String.valueOf(lista.get(indiceActual).getTelefono()));
        }
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bPosteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPosteriorActionPerformed
        
        if (!(indiceActual == lista.size()-1)) {
            indiceActual ++;
            tfNombre.setText(lista.get(indiceActual).getNombre());
            tfEdad.setText(String.valueOf(lista.get(indiceActual).getEdad()));
            tfProfesion.setText(lista.get(indiceActual).getProfesion());
            tfTelefono.setText(String.valueOf(lista.get(indiceActual).getTelefono()));
        }
    }//GEN-LAST:event_bPosteriorActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        EjercicioBaseDatos.volver();
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaOperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bPosterior;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfProfesion;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
