/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datobase.exceptions.NonexistentEntityException;
import ejerciciobasedatos5.EjercicioBaseDatos5;
import javax.swing.JOptionPane;
import excepciones.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author txaber
 */
public class Vmenu extends javax.swing.JFrame {

    
    /**
     * Creates new form Vmenu
     */
    public Vmenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bGuardarEvento = new javax.swing.JButton();
        bBorrarEvento = new javax.swing.JButton();
        bModificarEvento = new javax.swing.JButton();
        bAsistencia = new javax.swing.JButton();
        bListado = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miGuardarEvento = new javax.swing.JMenuItem();
        miBorrarEvento = new javax.swing.JMenuItem();
        miModificarEvento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAsistencia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miListado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bGuardarEvento.setText("nuevo");
        bGuardarEvento.setFocusable(false);
        bGuardarEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bGuardarEvento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bGuardarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarEventoActionPerformed(evt);
            }
        });
        jToolBar1.add(bGuardarEvento);

        bBorrarEvento.setText("eliminar");
        bBorrarEvento.setFocusable(false);
        bBorrarEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBorrarEvento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBorrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarEventoActionPerformed(evt);
            }
        });
        jToolBar1.add(bBorrarEvento);

        bModificarEvento.setText("modificar");
        bModificarEvento.setFocusable(false);
        bModificarEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificarEvento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bModificarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarEventoActionPerformed(evt);
            }
        });
        jToolBar1.add(bModificarEvento);

        bAsistencia.setText("asistencia");
        bAsistencia.setFocusable(false);
        bAsistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAsistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsistenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAsistencia);

        bListado.setText("listar");
        bListado.setFocusable(false);
        bListado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListadoActionPerformed(evt);
            }
        });
        jToolBar1.add(bListado);

        bSalir.setText("salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("eventos");

        miGuardarEvento.setText("guardar evento");
        miGuardarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarEventoActionPerformed(evt);
            }
        });
        jMenu1.add(miGuardarEvento);

        miBorrarEvento.setText("borrar evento");
        miBorrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarEventoActionPerformed(evt);
            }
        });
        jMenu1.add(miBorrarEvento);

        miModificarEvento.setText("modificar evento");
        miModificarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarEventoActionPerformed(evt);
            }
        });
        jMenu1.add(miModificarEvento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("asistencia");

        miAsistencia.setText("control asistencia");
        miAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAsistenciaActionPerformed(evt);
            }
        });
        jMenu2.add(miAsistencia);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("listado");

        miListado.setText("listado");
        miListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListadoActionPerformed(evt);
            }
        });
        jMenu3.add(miListado);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miGuardarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarEventoActionPerformed
        EjercicioBaseDatos5.vEvento();
    }//GEN-LAST:event_miGuardarEventoActionPerformed

    private void miBorrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarEventoActionPerformed
        try {
            String nombre = JOptionPane.showInputDialog(this, "introduce nombre del evento a borrar");
            validar(nombre);
            
            EjercicioBaseDatos5.borrarEvento(nombre);
            
            JOptionPane.showMessageDialog(this, "operacion realizada con exito");
        }
        catch (DatoRequerido e) {
            JOptionPane.showMessageDialog(this, "no has introducido nada");
        }
        catch (DatoNoValido e) {
            JOptionPane.showMessageDialog(this, "el nombre no vale");
        }
        catch (NonexistentEntityException e) {
            JOptionPane.showMessageDialog(this, "no se encontro el evento");
        }
        catch(Exception e) {
            System.out.println(e.getClass()+""+e.getCause());
        }
    }//GEN-LAST:event_miBorrarEventoActionPerformed

    private void miModificarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarEventoActionPerformed
        try {
            String nombre = JOptionPane.showInputDialog(this, "introduce nombre del evento a modificar");
            validar(nombre);
            
            if (!EjercicioBaseDatos5.buscarEvento(nombre))
                throw new FilaNoEncontrada();
            
            EjercicioBaseDatos5.vOperacionConDatos(nombre);
        }
        catch (DatoRequerido e) {
            JOptionPane.showMessageDialog(this, "no has introducido nada");
        }
        catch (DatoNoValido e) {
            JOptionPane.showMessageDialog(this, "el nombre no vale");
        }
        catch (FilaNoEncontrada e) {
            JOptionPane.showMessageDialog(this, "no se encontro el evento");
        }
        catch(Exception e) {
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_miModificarEventoActionPerformed

    private void bGuardarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarEventoActionPerformed
        miGuardarEvento.doClick();
    }//GEN-LAST:event_bGuardarEventoActionPerformed

    private void bBorrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarEventoActionPerformed
        miBorrarEvento.doClick();
    }//GEN-LAST:event_bBorrarEventoActionPerformed

    private void bModificarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarEventoActionPerformed
        miModificarEvento.doClick();
    }//GEN-LAST:event_bModificarEventoActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        EjercicioBaseDatos5.salir();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsistenciaActionPerformed
        miAsistencia.doClick();
    }//GEN-LAST:event_bAsistenciaActionPerformed

    private void miAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAsistenciaActionPerformed
        EjercicioBaseDatos5.vAsistencia();
    }//GEN-LAST:event_miAsistenciaActionPerformed

    private void miListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListadoActionPerformed
        EjercicioBaseDatos5.vListado();
    }//GEN-LAST:event_miListadoActionPerformed

    private void bListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListadoActionPerformed
        miListado.doClick();
    }//GEN-LAST:event_bListadoActionPerformed

    private void validar(String nombre) throws Exception{
        
        if (nombre.isEmpty())
            throw new DatoRequerido();
            
        Pattern patt = Pattern.compile("[a-zA-Z0-9 ]*");
        Matcher matt = patt.matcher(nombre);
        if (!matt.matches())
            throw new DatoNoValido();
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsistencia;
    private javax.swing.JButton bBorrarEvento;
    private javax.swing.JButton bGuardarEvento;
    private javax.swing.JButton bListado;
    private javax.swing.JButton bModificarEvento;
    private javax.swing.JButton bSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem miAsistencia;
    private javax.swing.JMenuItem miBorrarEvento;
    private javax.swing.JMenuItem miGuardarEvento;
    private javax.swing.JMenuItem miListado;
    private javax.swing.JMenuItem miModificarEvento;
    // End of variables declaration//GEN-END:variables
}
