/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import ejerciciobasedatos2.EjercicioBaseDatos2;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import excepciones.*;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
/**
 *
 * @author txaber
 */
public class Veventos extends javax.swing.JDialog {

    // variable para expecificar el comportamiento de esta ventana
    private int operacion;
    
    /**
     * Creates new form Veventos
     */
    public Veventos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        operacion = 1;
    }
    
    public Veventos(java.awt.Frame parent, boolean modal, String nombre, String lugar, LocalDate fecha , LocalTime horaInicio, LocalTime horaFin, int maxPersonas) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        tfNombre.setText(nombre);
        tfLugar.setText(lugar);
        tfFecha.setText(fecha.toString());
        tfLugar.setText(horaInicio.toString());
        tfLugar.setText(horaFin.toString());
        tfLugar.setText(String.valueOf(maxPersonas));
        tfNombre.setEditable(false);
        
        operacion = 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNombre = new javax.swing.JTextField();
        tfLugar = new javax.swing.JTextField();
        tfFecha = new javax.swing.JTextField();
        tfHoraInicio = new javax.swing.JTextField();
        tfHoraFin = new javax.swing.JTextField();
        tfMaxPersonas = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bAceptar.setText("aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FUTUROS EVENTOS");

        jLabel3.setText("lugar");

        jLabel4.setText("fecha");

        jLabel5.setText("hora inicio");

        jLabel6.setText("hora termina");

        jLabel7.setText("max personas");

        bVolver.setText("volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bVolver, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfFecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfHoraInicio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfHoraFin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfMaxPersonas, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaxPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bVolver))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            validarDatos();
            
            if (operacion == 1)
                alta();
            else
                modificar();
        }
        catch (DatoRequerido e) {
            JOptionPane.showMessageDialog(this, "falta introducir datos");
        }
        catch (DatoNoValido e) {
            JOptionPane.showMessageDialog(this, "los datos introducidos son incorrectos");
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "se encontro numero pero fallo al convertir");
        }
        catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "error en el formato de de fecha u hora");
        }
        catch (MySQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "un evento con ese nombre ya existe");
        }
        catch(ErrorBaseDatos e) {
            JOptionPane.showMessageDialog(this, "no se pudo actualizar base de datos debido a un error desconocido");
        }
        catch (Exception e) {
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed

    private void alta() throws Exception {
            
            DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate fecha = LocalDate.parse(tfFecha.getText(),formatoFecha);
            
            DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime horaInicio = LocalTime.parse(tfHoraInicio.getText(), formatoHora);
            LocalTime horaFin = LocalTime.parse(tfHoraFin.getText(), formatoHora);
            
            int max = Integer.parseInt(tfMaxPersonas.getText());
            
            EjercicioBaseDatos2.altaEventos(tfNombre.getText(), tfLugar.getText(), fecha, horaInicio, horaFin, max);
            JOptionPane.showMessageDialog(this, "operacion(alta) realizada correctamente");
    }
    
    private void modificar() throws Exception {
        
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fecha = LocalDate.parse(tfFecha.getText(),formatoFecha);
        
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime horaInicio = LocalTime.parse(tfHoraInicio.getText(), formatoHora);
        LocalTime horaFin = LocalTime.parse(tfHoraFin.getText(), formatoHora);
        
        int max = Integer.parseInt(tfMaxPersonas.getText());
        
        int res = EjercicioBaseDatos2.modificarEvento(tfLugar.getText(), fecha, horaInicio, horaFin, max);
        JOptionPane.showMessageDialog(this, "operacion(modificar) realizada correctamente, se modificaron "+res+" filas");
        this.dispose();
    }
     
    private void validarDatos() throws Exception{
        
        // mirar si esta vacio
        if (tfNombre.getText().isEmpty() || tfLugar.getText().isEmpty() || tfFecha.getText().isEmpty() || 
            tfHoraInicio.getText().isEmpty() || tfHoraFin.getText().isEmpty() || tfMaxPersonas.getText().isEmpty())
            throw new DatoRequerido();
        
        // pattern y matcher
        Pattern patt = Pattern.compile("[a-zA-Z0-9 ]*");
        Matcher matt = patt.matcher(tfNombre.getText());
        if (!matt.matches())
            throw new DatoNoValido();
        
        matt = patt.matcher(tfLugar.getText());
        if (!matt.matches())
            throw new DatoNoValido();
        
        patt = Pattern.compile("[0-9]*");
        matt = patt.matcher(tfMaxPersonas.getText());
        if (!matt.matches() || tfMaxPersonas.getText().length() > 3 ||tfMaxPersonas.getText().length() <= 0)
            throw new DatoNoValido();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Veventos dialog = new Veventos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfHoraFin;
    private javax.swing.JTextField tfHoraInicio;
    private javax.swing.JTextField tfLugar;
    private javax.swing.JTextField tfMaxPersonas;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
