/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import ejerciciobasedatos3.EjercicioBaseDatos3;
import javax.swing.JOptionPane;

/**
 *
 * @author txaber
 */
public class VconsultaCasos extends javax.swing.JDialog {

    /**
     * Creates new form VconsultaCasos
     */
    public VconsultaCasos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbCli = new javax.swing.JRadioButton();
        rbAbo = new javax.swing.JRadioButton();
        rbID = new javax.swing.JRadioButton();
        lIndicador = new javax.swing.JLabel();
        tfEntrada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSalida = new javax.swing.JTextArea();
        bOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Consultar casos");

        buttonGroup1.add(rbCli);
        rbCli.setText("Por dni de cliente");
        rbCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCliActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAbo);
        rbAbo.setText("Por dni de abogado");
        rbAbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAboActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbID);
        rbID.setText("Por id caso");
        rbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDActionPerformed(evt);
            }
        });

        lIndicador.setText("dni de cliente");

        tfEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEntradaFocusLost(evt);
            }
        });

        taSalida.setColumns(20);
        taSalida.setRows(5);
        jScrollPane1.setViewportView(taSalida);

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lIndicador)
                            .addGap(18, 18, 18)
                            .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bOK)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(52, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCli)
                        .addGap(33, 33, 33)
                        .addComponent(rbAbo)
                        .addGap(18, 18, 18)
                        .addComponent(rbID))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCli)
                    .addComponent(rbAbo)
                    .addComponent(rbID))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIndicador)
                    .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(bOK)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_bOKActionPerformed

    private void rbCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCliActionPerformed
        if(rbCli.isSelected()) {
            lIndicador.setText("dni de cliente:");
            tfEntrada.setText("");
            taSalida.setText("");
        }
    }//GEN-LAST:event_rbCliActionPerformed

    private void rbAboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAboActionPerformed
        if(rbAbo.isSelected()) {
            lIndicador.setText("dni de abogado:");
            tfEntrada.setText("");
            taSalida.setText("");
        }
    }//GEN-LAST:event_rbAboActionPerformed

    private void rbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDActionPerformed
        if(rbID.isSelected()) {
            lIndicador.setText("identificador:");
            tfEntrada.setText("");
            taSalida.setText("");
        }
    }//GEN-LAST:event_rbIDActionPerformed

    private void tfEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEntradaFocusLost
        try {
            if (rbCli.isSelected()) {
                EjercicioBaseDatos3.consultaCasoPorDniCli(tfEntrada.getText());
                EjercicioBaseDatos3.llenarCasoCliente(taSalida);
            }
            else {    
                if (rbAbo.isSelected()) {
                    EjercicioBaseDatos3.consultaCasoPorDniAbo(tfEntrada.getText());
                    EjercicioBaseDatos3.llenarCasoAbogado(taSalida);
                }
                else {
                    if (rbID.isSelected()) {
                        EjercicioBaseDatos3.consultaCasoPorID(tfEntrada.getText());
                        EjercicioBaseDatos3.llenarCaso(taSalida);
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "no has seleccionado ninguna opcion");
                    }
                }
            }
            
        }
        catch (Exception e) {
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_tfEntradaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VconsultaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VconsultaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VconsultaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VconsultaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VconsultaCasos dialog = new VconsultaCasos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lIndicador;
    private javax.swing.JRadioButton rbAbo;
    private javax.swing.JRadioButton rbCli;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JTextArea taSalida;
    private javax.swing.JTextField tfEntrada;
    // End of variables declaration//GEN-END:variables
}
