/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author txaber
 */
import ejerciciobasedatos3.EjercicioBaseDatos3;
        
public class Vprincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form Vprincipal
     */
    public Vprincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCliAlta = new javax.swing.JMenuItem();
        miCliBaja = new javax.swing.JMenuItem();
        miCliModif = new javax.swing.JMenuItem();
        miCliConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAboAlta = new javax.swing.JMenuItem();
        miAboBaja = new javax.swing.JMenuItem();
        miAboModif = new javax.swing.JMenuItem();
        miAboConsulta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miCasAlta = new javax.swing.JMenuItem();
        miCasBaja = new javax.swing.JMenuItem();
        miCasTerm = new javax.swing.JMenuItem();
        miCasModif = new javax.swing.JMenuItem();
        miCasConsulta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("clientes");

        miCliAlta.setText("alta");
        miCliAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCliAltaActionPerformed(evt);
            }
        });
        jMenu1.add(miCliAlta);

        miCliBaja.setText("baja");
        miCliBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCliBajaActionPerformed(evt);
            }
        });
        jMenu1.add(miCliBaja);

        miCliModif.setText("modificar");
        miCliModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCliModifActionPerformed(evt);
            }
        });
        jMenu1.add(miCliModif);

        miCliConsulta.setText("consultar");
        miCliConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCliConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(miCliConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("abogados");

        miAboAlta.setText("alta");
        miAboAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboAltaActionPerformed(evt);
            }
        });
        jMenu2.add(miAboAlta);

        miAboBaja.setText("baja");
        miAboBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboBajaActionPerformed(evt);
            }
        });
        jMenu2.add(miAboBaja);

        miAboModif.setText("modificar");
        miAboModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboModifActionPerformed(evt);
            }
        });
        jMenu2.add(miAboModif);

        miAboConsulta.setText("consultar");
        miAboConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(miAboConsulta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("casos");

        miCasAlta.setText("alta");
        miCasAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCasAltaActionPerformed(evt);
            }
        });
        jMenu3.add(miCasAlta);

        miCasBaja.setText("baja");
        miCasBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCasBajaActionPerformed(evt);
            }
        });
        jMenu3.add(miCasBaja);

        miCasTerm.setText("terminar");
        miCasTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCasTermActionPerformed(evt);
            }
        });
        jMenu3.add(miCasTerm);

        miCasModif.setText("modificar");
        miCasModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCasModifActionPerformed(evt);
            }
        });
        jMenu3.add(miCasModif);

        miCasConsulta.setText("consultar");
        miCasConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCasConsultaActionPerformed(evt);
            }
        });
        jMenu3.add(miCasConsulta);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("salir");

        miSalir.setText("abandonar programa");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu4.add(miSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCliBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCliBajaActionPerformed
        vcambioPer = new VcambioPersona(this,true,"cliente","baja");
        vcambioPer.setVisible(true);
    }//GEN-LAST:event_miCliBajaActionPerformed

    private void miAboModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAboModifActionPerformed

    private void miCasModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCasModifActionPerformed
        vModificarCaso = new VmodificarCaso(this,true);
        vModificarCaso.setVisible(true);
    }//GEN-LAST:event_miCasModifActionPerformed
        
    private void miCliAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCliAltaActionPerformed
        vcambioPer = new VcambioPersona(this,true,"cliente","alta");
        vcambioPer.setVisible(true);
    }//GEN-LAST:event_miCliAltaActionPerformed

    private void miCliModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCliModifActionPerformed
        vcambioPer = new VcambioPersona(this,true,"cliente","modificar");
        vcambioPer.setVisible(true);
    }//GEN-LAST:event_miCliModifActionPerformed

    private void miCliConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCliConsultaActionPerformed
        vconsultaPer = new VconsultaPersona(this,true,"Cliente");
        vconsultaPer.setVisible(true);
    }//GEN-LAST:event_miCliConsultaActionPerformed

    private void miAboAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAboAltaActionPerformed

    private void miAboBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAboBajaActionPerformed

    private void miAboConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAboConsultaActionPerformed

    private void miCasAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCasAltaActionPerformed
        vAltaCaso = new ValtaCaso(this,true);
        vAltaCaso.setVisible(true);
    }//GEN-LAST:event_miCasAltaActionPerformed

    private void miCasBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCasBajaActionPerformed
        vBajaCaso = new VbajaCaso(this,true);
        vBajaCaso.setVisible(true);
    }//GEN-LAST:event_miCasBajaActionPerformed

    private void miCasConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCasConsultaActionPerformed
        vConsultaCaso = new VconsultaCasos(this,true);
        vConsultaCaso.setVisible(true);
    }//GEN-LAST:event_miCasConsultaActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        EjercicioBaseDatos3.salir();
    }//GEN-LAST:event_miSalirActionPerformed

    private void miCasTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCasTermActionPerformed
        vTerminarCaso = new VterminarCaso(this,true);
        vTerminarCaso.setVisible(true);
    }//GEN-LAST:event_miCasTermActionPerformed

    
    private static VcambioPersona vcambioPer;
    private static VconsultaPersona vconsultaPer;
    private static ValtaCaso vAltaCaso;
    private static VbajaCaso vBajaCaso;
    private static VterminarCaso vTerminarCaso;
    public static VmodificarCaso vModificarCaso;
    public static VconsultaCasos vConsultaCaso;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAboAlta;
    private javax.swing.JMenuItem miAboBaja;
    private javax.swing.JMenuItem miAboConsulta;
    private javax.swing.JMenuItem miAboModif;
    private javax.swing.JMenuItem miCasAlta;
    private javax.swing.JMenuItem miCasBaja;
    private javax.swing.JMenuItem miCasConsulta;
    private javax.swing.JMenuItem miCasModif;
    private javax.swing.JMenuItem miCasTerm;
    private javax.swing.JMenuItem miCliAlta;
    private javax.swing.JMenuItem miCliBaja;
    private javax.swing.JMenuItem miCliConsulta;
    private javax.swing.JMenuItem miCliModif;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
